# Setup
title:               Adam Heinrich
tagline:             "Embedded SW &amp; HW"

url:                 https://www.adamh.cz
baseurl:             ""

# Permalinks
permalink:           /blog/:year/:month/:title/

# Posts
excerpt_separator:   <!--more-->
paginate:            5
paginate_path:       "/blog/page:num/"

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# Local server
hostname:            localhost
port:                4000

# Social networks
disqus:
  username:          adamheinrich

twitter:
  username:          adamheinrich

github:
  repository:        https://github.com/adamheinrich/adamh.cz

# About & contact
author:
  name:              Adam Heinrich
  url:               https://www.adamh.cz
  email:             adam@adamh.cz

gems:                [jekyll-paginate]